steps:
  # Build Agent
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/smartsolve-agent', '-f', 'Dockerfile.agent', '.']
  
  # Build Backend  
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/smartsolve-backend', '-f', 'Dockerfile.backend', '.']
  
  # Build Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/smartsolve-frontend', '-f', 'Dockerfile.frontend', '.']

  # Push images
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/smartsolve-agent']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/smartsolve-backend']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/smartsolve-frontend']

  # Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'smartsolve-agent', '--image', 'gcr.io/$PROJECT_ID/smartsolve-agent', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'smartsolve-backend', '--image', 'gcr.io/$PROJECT_ID/smartsolve-backend', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']
  
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['run', 'deploy', 'smartsolve-frontend', '--image', 'gcr.io/$PROJECT_ID/smartsolve-frontend', '--region', 'us-central1', '--platform', 'managed', '--allow-unauthenticated']

images:
  - 'gcr.io/$PROJECT_ID/smartsolve-agent'
  - 'gcr.io/$PROJECT_ID/smartsolve-backend'
  - 'gcr.io/$PROJECT_ID/smartsolve-frontend'